### ISSUE TITLE
Csunplugged Activities selection

### ISSUE THREAD

**Issue by srohilla** [srohilla/CodeSpanners#11]

**Comment by virajnilakh** [comment]
![img-20160918-wa0006](https://cloud.githubusercontent.com/assets/19594983/18619946/3d580a7e-7e26-11e6-9be0-8749ac23ead2.jpg)

**Comment by amaydubey** [comment]
For activities selection, we thouroughly went through all the activities mentioned on CSUnplugged. Further, we eliminated a number of activities and finalized two activities: Sorting Algorithms and Minimal Spanning Tree. For both of these, we saw a number of videos explaining the games.

For sorting algorithms, one of the videos we saw was sorting of fruits in between players. This game can be played between 3 or more players, with the complexity of the solving algorithm increasing with the number of players. The game requires fruits, twice but one the number of players, so that each player but one gets two fruits each. The remaining player gets one fruit. The fruits are distributed randomly. When the game starts, the players form a circle. Each player is given an objective fruit(the fruit which they should finally hold, at the end of the game). The objective is to get each player their objective fruit. The fruits can only be exchanged by players standing adjacently, only if one of these players has an empty hand.

For Minimal Spanning tree, the video we saw was for Muddy City. In this game, each of the players has to find a way to connect all the houses(nodes) with the minimum cost. Every two houses or buildings are connected directly or indirectly. All the directly connected houses have a cost of building pavement between them. The players need to find a way to traverse the whole city so that none of the buildings are left, with the minimum cost of building pavement.

Consequently, we got to the decision of designing and developing our game on the principle of Minimal Spanning Tree.
